server:
  port: 8087
#logging.file=user.log

spring:
  data:
    mongodb:
      host: 192.168.99.100
      database: user
      port: 27017

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web:
          client: DEBUG
      koenighotze: DEBUG

security:
  user:
    name: user
    password: user