language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: JJGMlXTmPGhss+bS9mvKw+JxaOF05hwyIHDdvkgwZ0se6YT5uL7T+KZikmHoOL+sN1FCkRroQ1w0WPHIlHxFphPGE3cEdOPvdWJUx6NKGS0xGUR0yZuIvUvKPuB6gTgRltAyye3MArqxuFTkMS2CnpSbmDLsW0h3xQnXM1NRlngkHTZuATesqYc6M9UXsnC4Kto7k56GNLc0sVwA39IIw9Yw6EItGTVnZAErpb++NeI8/tjBhD8b5LcuXmiBB3de3pFUuMfphfkl82c8S1oUB+ZB1ijPx9+rKcGtd+D3keE5GzFwJ1mrQtPg77LAW47psnEKO7xSDCoPtHEt2dvNoi8XvR5rxiuevIdMAsvKOMOKxgFsT7HjlQskpDiztjhdhEi1bXs0hF9+MVrJzijCGWb3Bkrd0/TTcyLCotcyn6+iDiWuasnDw9ygP8UMaGF1t+l56IETu+mtiqzcs9fYmfsMHtiYxo1gXXpmEQHQLXEUFrCXIqNXk8FSfBBsj8CUTwLO8JXK+n8kJGRf/mUjN3yD9q6D9WQ4xyfIxyyPMxNq6p9XVeLupSvWAfZrCcZa1PCTmdjp+70rbRWHIfrxL0c0lG5hgm9DS4zm4gMJ3xSA8euAWn5Kir8nWkbq91B4/nLsxtqXogL5wgNc2tH22mqLcj0qRRe6jaC9NgW1dZc=
