server:
  port: 8098

spring:

  data:
    mongodb:
      host: localhost
      database: livefeed
      port: 27017
  jackson:
    serialization:
      indent_output: true
  main:
    banner-mode: "off"

logging:
  config: classpath:logback-spring.xml

debug: true